### ISSUE TITLE
Not working on PC 2?

### ISSUE THREAD

**Issue by CodeNemo** [orangepi-xunlong/wiringOP#1]
After installation:
> root@OrangePi:~# gpio -v
gpio version: 2.46
Copyright (c) 2012-2018 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty
Device tree is enabled.
--> Xunlong Orange Pi PC 2

My test code:
> #include <wiringPi.h>
int main()
{
    wiringPiSetup();
    pinMode(5, INPUT);
    while(1)
    {
        delay(100);
        printf("%d", digitalRead(5));
    }
    return 0;
}

Compiled and ran, no any outputs.

> root@OrangePi:~# gpio readall
 +------+-----+----------+------+---+OrangePi RK3399---+---+------+---------+-----+--+

Why RK3399 but not H5?

**Comment by vatanuki** [comment]
set correct PLATFORM to OrangePi_PC2 or OrangePi_H5, default is OrangePi_RK3399 - thats why
