### ISSUE TITLE
Using multiple spi devices

### ISSUE THREAD

**Issue by dolfandringa** [orangepi-xunlong/wiringOP#10]
Im WiringPiSPI.c I see you can specify the spi channel, where 0 corresponds to `/dev/spidev0.0` and 1 corresponds to `/dev/spidev1.0`. But on at least the orangePi Zero, you can enable multiple chipselect pins in the dtb overlays. I have managed to also add `/dev/spidev1.1` and `/dev/spidev1.2`. How can I use those spi devices? If there is no way to do this currently, would it be an idea to add a `port` option (aside from the channel) defaulting to `0` which allows using `channel.port` for the spi device? I'd be happy to create a PR for this.

**Comment by orangepi-xunlong** [comment]
Hi,

welcome to this, in addition, could you please provide the detailed test steps and information, as well as the version of the operating system you are using, thanks!
