### ISSUE TITLE
IC2 Support

### ISSUE THREAD

**Issue by philbertphotos** [orangepi-xunlong/wiringOP#18]
Will IC2 ever be supported?

**Comment by leeboby** [comment]
Sure, 

[https://github.com/orangepi-xunlong/wiringOP/blob/master/examples/oled_demo.c](url) 
[https://github.com/orangepi-xunlong/wiringOP/blob/master/wiringPi/oled.c](url)

 can serve as a reference. 

In addition, you need to ensure that the image you are using is visible to the i2C device node under /dev.
