### ISSUE TITLE
OrangePi3 H6 Support?

### ISSUE THREAD

**Issue by sadnblueish** [orangepi-xunlong/wiringOP#2]
any plan for development? Armbian community is working aggressively on OPi3 for general usage and it is being promoted. It will be a nice add-on to OPi3

**Comment by FLYBYME** [comment]
There is some support but its mostly broken..

https://github.com/orangepi-xunlong/wiringOP/blob/master/wiringPi/OrangePi.c#L683

**Comment by orangepi-xunlong** [comment]
Have support！
