### ISSUE TITLE
Wiring OP For Android Development

### ISSUE THREAD

**Issue by AhmadPanogari** [orangepi-xunlong/wiringOP#21]
Hello, 
I have OrangePi 4B run on Android.

Can this be used for Android? and how to use the library for making Android applications?

**Comment by orangepi-xunlong** [comment]
Sorry, It's just for linux. For android, please refer to this app

https://drive.google.com/drive/folders/1TV_E0MQf7GxIx2CV66RybKG-LwmOnSW3
