### ISSUE TITLE
zero-plus-h5 cannot use PWM

### ISSUE THREAD

**Issue by kluoyun** [orangepi-xunlong/wiringOP#25]
官方例程里面的pwm.c运行结果
我的板子是zeroplus h5 查看用户手册发现pwm1是第7脚，然后运行结果就是这样的，pin为6或者7都不行
the pin you choose is not surport hardware PWM
you can select PI3 for PWM pin
or you can use it in softPwm mode
please use soft pwmmode or choose PWM pin

**Comment by alexgubanow** [comment]
Hello @kluoyun pwm is supported on limited amount of boards. I suggest you try use soft pwm, other wise it is hard fix code of library , so it will be universal in same time and implement pwm for each board.
