### ISSUE TITLE
GPIO failure on orange pi 4 (RK3399)

### ISSUE THREAD

**Issue by cristol30** [orangepi-xunlong/wiringOP#30]
Hello, 

Only gpio 50 (gpio1_c2) work 
![Screenshot_20201209_085104](https://user-images.githubusercontent.com/75731362/101624608-73b90c80-3a1a-11eb-8916-7bea61a97ea8.jpg)

For example i can't declare gpio 35 (gpio1_a3)
GPIO 149 (gpio4_c5 ) can be declared but it's stay on 0 state when i push a button.

Can you see that ?

Thanks you 👍

**Comment by baiywt** [comment]
You should use wPi number instead of gpio number, The WRI corresponding to GPIO4_C5 is 16.
root@orangepi4:~/WiringOP# gpio read 16
1
root@orangepi4:~/WiringOP# gpio read 16
0
