### ISSUE TITLE
How to use Visual Studio 2019 (Windows 10) to develope for Orange Pi Lite ?

### ISSUE THREAD

**Issue by HyVong007** [orangepi-xunlong/wiringOP#31]
I want to code C++ in Visual Studio 2019 on Windows with full Intellisense, highlighting, code suggestion.... and then transfer via SSH to Orange Pi Lite and run.
Do i need to get DLL files of wiringOP ? How to make Intellisense suggest with wiringOP ?
thank in advance !

**Comment by orangepi-xunlong** [comment]
Sorry, we have no experience in this field.
