### ISSUE TITLE
Orange pi 4B build err multiple definition of 'comDat'; drcNet.o

### ISSUE THREAD

**Issue by AndreiCherniaev** [orangepi-xunlong/wiringOP#35]
I try build wiringPi for Orange pi 4B on Ubuntu 20 with GCC 10.2 but
multiple definition of 'comDat'; drcNet.o:(.bss+0x400): first defined here

This is because drcNetCmd.h
1) Need #pragma once
2) Need typedef for struct. This is right code:
**typedef** struct drcNetComStruct
{
  uint32_t pin ;
  uint32_t cmd ;
  uint32_t data ;
} comDat ;

**Comment by orangepi-xunlong** [comment]
Thank you. It has been corrected！
