### ISSUE TITLE
香橙派4lts在debian11系统下调用wiringOP内部函数pullUpDnControl(CMT2300A_nIRQ,PUD_DOWN);函数时出现段错误

### ISSUE THREAD

**Issue by victorlingfeng** [orangepi-xunlong/wiringOP#57]
香橙派4lts在debian11系统 Orangepi4-lts_3.0.6_debian_bullseye_desktop_xfce_linux5.10.43下调用wiringOP内部函数pullUpDnControl(CMT2300A_nIRQ,PUD_DOWN);函数时出现段错误，最后定位在函数 pullUpDnControl内部*(gpio + GPPUD)              = pud & 3 ;这个语句执行报错。

**Comment by orangepi-xunlong** [comment]
pullUpDnControl 是没有适配的

**Comment by notcaremath** [comment]
遇到同样的问题，什么时候会适配，希望能得到计划时间

**Comment by baiywt** [comment]
已适配https://github.com/orangepi-xunlong/wiringOP/commit/1fa13213f6b8e4eec7311779092545d6e5dbaa37
