### ISSUE TITLE
Orange pi Zero

### ISSUE THREAD

**Issue by atulgo** [orangepi-xunlong/wiringOP#6]
Hi
Is it required to define a value 'PLATFORM' as 'OrangePi_ZERO' in Makefile.
Or required to define an env variable 'PLATFORM' in shell.

Please look at line 47 of "wiringOP/gpio/Makefile" and
 line 54 in "wiringOP/wiringPi/Makefile"

regards

**Comment by tropikhajma** [comment]
the below patch seems to work here

[zero.log](https://github.com/orangepi-xunlong/wiringOP/files/4209797/zero.log)

**Comment by orangepi-xunlong** [comment]
The problem has been fixed.
