### ISSUE TITLE
[Bug] Wrong Pin annotation on OPi Zero 2

### ISSUE THREAD

**Issue by soimy** [orangepi-xunlong/wiringOP#60]
https://github.com/orangepi-xunlong/wiringOP/blob/c56902108e78fd5dfd4fdb9499488c2f83988de2/README.md?plain=1#L318
https://github.com/orangepi-xunlong/wiringOP/blob/0a7284942375ff68a9940c44234b6d6ec5f7aa59/gpio/OrangePi.c#L717
According to the user manual and real testing, Orange Pi Zero 2's Physical pin 25 shall be 3.3V, not GND. Could be dangerous.

**Comment by orangepi-xunlong** [comment]
Are you sure you know where pin 25 is？

![图片](https://user-images.githubusercontent.com/10287101/208831946-c0947914-ed28-46fe-8f8a-ee79d7a6b65a.png)

**Comment by soimy** [comment]
Oh, my mistake...  there is no 27-33 pin on zero2. I counted from bottom actually
