### ISSUE TITLE
Orange PI 5: pull up/down resistor setup doesn't work

### ISSUE THREAD

**Issue by GuglielmiAndrea** [orangepi-xunlong/wiringOP#80]
Hello,
I'm using wiringOP successfully to handle GPIO of Orange PI 5 but I'm not able to configure pull-down resistor, it seems by default pull-up resistor is enabled for all inputs.
It's not so nice because I should apply a strong pull-down resistor externally to get low level normally draining more current for nothing.
Please can you help me to make it working somehow, or at least to disable pull-up default mode?
Tri state would be enough applying a resistor my side.
Thanks
Andrea

**Comment by leeboby** [comment]
If you are using a Linux image released by OrangePi, it comes pre-installed with WiringOP and supports pull-up/down resistors by default.

The user manual contains instructions on how to use WiringOP.

**Comment by GuglielmiAndrea** [comment]
Thanks, I will try again, but anyhow, where I can find source code of that implementation? I need to integrate it in a custom C application, strange it is not available. Can you give me the link? the repository?

**Comment by leeboby** [comment]
https://github.com/orangepi-xunlong/wiringOP/commit/e6a192f7cc08b8a892cdbe5c07ad89f8ae8a6471
